%package -n patterns-sailfish-device-configuration-i4213
Summary: Jolla Configuration i4213
Requires: patterns-sailfish-device-configuration-common-i4213
Requires: patterns-sailfish-device-adaptation-mermaid

Requires: droid-config-i4213-sailfish
Requires: droid-config-i4213-pulseaudio-settings
Requires: droid-config-i4213-policy-settings
Requires: droid-config-i4213-preinit-plugin
Requires: droid-config-i4213-flashing
Requires: droid-config-i4213-bluez5
Requires: droid-hal-version-i4213

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-networking-multisim
Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-i4213
Pattern with packages for i4213 configurations

%files -n patterns-sailfish-device-configuration-i4213
