%package -n patterns-sailfish-device-configuration-i3213
Summary: Jolla Configuration i3213
Requires: patterns-sailfish-device-configuration-common-i3213
Requires: patterns-sailfish-device-adaptation-mermaid

Requires: droid-config-i3213-sailfish
Requires: droid-config-i3213-pulseaudio-settings
Requires: droid-config-i3213-policy-settings
Requires: droid-config-i3213-preinit-plugin
Requires: droid-config-i3213-flashing
Requires: droid-config-i3213-bluez5
Requires: droid-hal-version-i3213

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-i3213
Pattern with packages for i3213 configurations

%files -n patterns-sailfish-device-configuration-i3213
