%package -n patterns-sailfish-device-configuration-xqau51
Summary: Jolla Configuration xqau51
Requires: patterns-sailfish-device-configuration-common-xqau51
Requires: patterns-sailfish-device-adaptation-pdx201

Requires: droid-config-xqau51-sailfish
Requires: droid-config-xqau51-pulseaudio-settings
Requires: droid-config-xqau51-policy-settings
Requires: droid-config-xqau51-preinit-plugin
Requires: droid-config-xqau51-flashing
Requires: droid-config-xqau51-bluez5
Requires: droid-hal-version-xqau51

Requires: patterns-sailfish-cellular-apps

# NFC
Requires: jolla-settings-system-nfc
Requires: nfcd-dbuslog-plugin
Requires: nfcd-mce-plugin

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

%description -n patterns-sailfish-device-configuration-xqau51
Pattern with packages for xqau51 configurations

%files -n patterns-sailfish-device-configuration-xqau51
