%package -n patterns-sailfish-device-configuration-xqau52
Summary: Jolla Configuration xqau52
Requires: patterns-sailfish-device-configuration-common-xqau52
Requires: patterns-sailfish-device-adaptation-pdx201

Requires: droid-config-xqau52-sailfish
Requires: droid-config-xqau52-pulseaudio-settings
Requires: droid-config-xqau52-policy-settings
Requires: droid-config-xqau52-preinit-plugin
Requires: droid-config-xqau52-flashing
Requires: droid-config-xqau52-bluez5
Requires: droid-hal-version-xqau52

Requires: patterns-sailfish-cellular-apps

# NFC
Requires: jolla-settings-system-nfc
Requires: nfcd-dbuslog-plugin
Requires: nfcd-mce-plugin

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-networking-multisim
Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

%description -n patterns-sailfish-device-configuration-xqau52
Pattern with packages for xqau52 configurations

%files -n patterns-sailfish-device-configuration-xqau52
