%package -n patterns-sailfish-device-configuration-i3113
Summary: Jolla Configuration i3113
Requires: patterns-sailfish-device-configuration-common-i3113
Requires: patterns-sailfish-device-adaptation-kirin

Requires: droid-config-i3113-sailfish
Requires: droid-config-i3113-pulseaudio-settings
Requires: droid-config-i3113-policy-settings
Requires: droid-config-i3113-preinit-plugin
Requires: droid-config-i3113-flashing
Requires: droid-config-i3113-bluez5
Requires: droid-hal-version-i3113

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-i3113
Pattern with packages for i3113 configurations

%files -n patterns-sailfish-device-configuration-i3113
