%package -n patterns-sailfish-device-configuration-i4113
Summary: Jolla Configuration i4113
Requires: patterns-sailfish-device-configuration-common-i4113
Requires: patterns-sailfish-device-adaptation-kirin

Requires: droid-config-i4113-sailfish
Requires: droid-config-i4113-pulseaudio-settings
Requires: droid-config-i4113-policy-settings
Requires: droid-config-i4113-preinit-plugin
Requires: droid-config-i4113-flashing
Requires: droid-config-i4113-bluez5
Requires: droid-hal-version-i4113

Requires: patterns-sailfish-cellular-apps

Requires: sailfish-content-graphics-z%{icon_res}

Requires: jolla-settings-networking-multisim
Requires: jolla-settings-system-flashlight

Requires: geoclue-provider-mlsdb
Requires: mapplauncherd-booster-silica-qt5-media

# NFC
Requires: nfcd-mce-plugin
Requires: nfcd-dbuslog-plugin
Requires: jolla-settings-system-nfc

%description -n patterns-sailfish-device-configuration-i4113
Pattern with packages for i4113 configurations

%files -n patterns-sailfish-device-configuration-i4113
